services:
  postgres_db:
    image: postgres:15
    container_name: postgres_voces
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./data_voces:/var/lib/postgresql/data
    networks:
      - voces-network
    restart: unless-stopped

networks:
  voces-network:
    driver: bridge